### ISSUE TITLE
Say hi

### ISSUE THREAD

**Issue by CrumpLab** [CrumpLab/rstatsmethods#1]
If you have completed the getting started assignment, please reply with a link to your github repository.

**Comment by celiaflorea** [comment]
Hi Dr. Crump, 

I think I have completed the first steps successfully: 
https://github.com/celiaflorea/7709GitTest

Look forward to meeting on Thursday! 

Best,
Celia

**Comment by CrumpLab** [comment]
Great, thanks Celia!

**Comment by yehudiskeller** [comment]
Good morning professor,

I have set up my accounts and followed the required first steps:
https://github.com/yehudiskeller/7709GitTest

-Yehudis

**Comment by karevalo29** [comment]
https://github.com/karevalo29/7709GitTest-Kristina

**Comment by CrumpLab** [comment]
Thanks Yehudis & Kristina!

**Comment by dmall24** [comment]
Good afternoon Professor Crump
my link is below
https://github.com/dmall24/7709gittestD

**Comment by SoyeonLeeBCCUNY** [comment]
Hello Professor Crump,
Here is my link
https://github.com/SoyeonLeeBCCUNY/7709GitTest
