### ISSUE TITLE
Git repository not an option when creating new project (MAC) 

### ISSUE THREAD

**Issue by karevalo29** [CrumpLab/rstatsmethods#2]
Hi all!
I ran into an issue that i'm not sure if anyone else has/had. When I went to create a new project in R after installing github desktop, I could not find the option to "create a git repository." My R studio could not find "git" in my computer. To fix this, I had to install Git on my Mac. To do this you have to mess with your computers terminal. 

1. Finder -> Applications -> Utilities -> Terminal

You have to install homebrew, which installs packages your computer may need that apple didn't. (fun fact: they also have other packages for fun things like gaming & such created by people here on github!)

2. Copy & paste this line of code directly into the terminal & hit return. It will ask you for your password to your computer, you just hit the buttons and press return, nothing will actually show up when you enter your password
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

3. It will take a few mins to fully install and then you enter this line of code and viola, your macbook now has git. 
brew install git

Just restart R studio and you will be good to go!

**Comment by SoyeonLeeBCCUNY** [comment]
Thank you for your help Kristina.
